---
title: "Welcome"
author: "Andrew Stewart"
date: "July 2021"
output: 
  html_document:
    theme: flatly
    toc: true
    toc_float: true
---
# Welcome

Welcome everyone to my R Course for the Open University.This page contains links to all the content that we'll be covering over the two days. There is a little bit of preparation work I'd like you to do in advance. Before the course itself I'd like you to watch a few brief videos introducing R and RStudio. R is the programming language itself, and RStudio is the interface we use to interact with the language. It's important that you have working installations of R and RStudio on your computers before the course starts, so if you have any trouble getting those two things up and running please let me know in advance. You can contact me via [email](emailto:drandrewjstewart@gmail.com) or direct message on Twitter [@ajstewart_lang](https://twitter.com/ajstewart_lang). 

First off, have a look at this video about the course.

Video 1 here - cover intro, overview of material, code along



## Technical Details
All of the material in this workshop was created using open source where possible. I used a ThinkPad running [GNU/Linux distro Ubuntu 20.04 LTS (Focal Fossa)](https://releases.ubuntu.com/20.04/). The audio was captured with a [Fifine USB Podcasting microphone](https://www.amazon.co.uk/Condenser-Microphone-Recording-Interface-Power-K669/dp/B01N034RTC/ref=sr_1_1_sspa?crid=141Z8ED4VGCVD&dchild=1&keywords=fifine+usb+podcast+condenser+microphone&qid=1594989611&sprefix=fifne+usb%2Caps%2C162&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFFMzAxOE5DUDJIREwmZW5jcnlwdGVkSWQ9QTA4MzA2NjIxVU40MlhNMFNCTDhWJmVuY3J5cHRlZEFkSWQ9QTA5NDI2OTQxOFY0R002UVJBS1AzJndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==) and the video with a [Razer Kiyo webcam](https://www.amazon.co.uk/Razer-Streaming-Adjustable-Brightness-Microphone/dp/B076QK6489/ref=sr_1_3?dchild=1&keywords=razer+kiyo&qid=1594989677&sr=8-3). The audio and video were recorded using [Open Broadcast Software](https://obsproject.com/) and edited using [Shotcut](https://shotcut.org/). The R code was written using [R 4.0.5](https://www.r-project.org/), and run in the [RStudio Desktop IDE](https://rstudio.com/products/rstudio/download/) version 1.4.1106.

The structure for this course was very much inspired by the [Sharing At Short Notice](https://rstudio.com/resources/webinars/sharing-on-short-notice-how-to-get-your-materials-online-with-r-markdown/) webinar by Alison Hill and Desirée De Leon.

The source code for each of the Workshops above is licensed under the [MIT license](https://opensource.org/licenses/MIT).